Revert "exfat: change to get file size from DataLength"
This reverts commit f9cc939cb063513fdf166aaa7a35aee2a76a50ed.

Log:
../fs/exfat/inode.c:469:36: warning: declaration of 'struct readahead_control' will not be visible outside of this function [-Wvisibility]
  469 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
../fs/exfat/inode.c:471:37: error: incomplete definition of type 'struct readahead_control'
  471 |         struct address_space *mapping = rac->mapping;
      |                                         ~~~^
../fs/exfat/inode.c:469:36: note: forward declaration of 'struct readahead_control'
  469 | static void exfat_readahead(struct readahead_control *rac)
      |                                    ^
../fs/exfat/inode.c:474:15: error: implicit declaration of function 'readahead_pos' [-Werror,-Wimplicit-function-declaration]
  474 |         loff_t pos = readahead_pos(rac);
      |                      ^
../fs/exfat/inode.c:479:29: error: implicit declaration of function 'readahead_length' [-Werror,-Wimplicit-function-declaration]
  479 |             ei->valid_size < pos + readahead_length(rac))
      |                                    ^
  CC      kernel/irq/dummychip.o
../fs/exfat/inode.c:482:2: error: implicit declaration of function 'mpage_readahead' [-Werror,-Wimplicit-function-declaration]
  482 |         mpage_readahead(rac, exfat_get_block);
      |         ^
  CC      drivers/base/power/generic_ops.o
../fs/exfat/inode.c:669:3: error: field designator 'readahead' does not refer to any field in type 'const struct address_space_operations'
  669 |         .readahead      = exfat_readahead,
      |         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 5 errors generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I5c941cb525963780c14c58f756fe934654d75675